### ISSUE TITLE
Missing from Chrome extension store

### ISSUE THREAD

**Issue by zeroxia** [gnulinooks/AliasLinks#12]
Can you update to official Chrome store?

Now I can copy the extension files from other computer to a new computer, and use "load unpacked" to load this extension on the new computer. But this is very inconvenient.

I tried to "pack extension" to create .crx file and drop the file to Chrome on new computer, Chrome always reports that the extention have been corrupted.

Thanks very much.

**Comment by roasher** [comment]
+1

**Comment by gnulinooks** [comment]
Sorry guys  for the trouble. Will update.

**Comment by gnulinooks** [comment]
Google changed policies some days back and I missed the notification. Have updated the extension as per their guidelines and submitted.

It says, it is under review and will be published once it gets cleared.

Sorry for the inconvenience.

**Comment by gnulinooks** [comment]
It is back on store guys :)  Please let me know if I should close this issue.
